services:
  postgres:
    image: postgres:14
    container_name: postgres-db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    profiles: ["core", "all"]

  python:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python-app
    volumes:
      - ./:/app
      - ./data:/app/data
    depends_on:
      - postgres
    networks:
      - app-network
    profiles: ["all"]

  jupyter:
    image: jupyter/datascience-notebook:latest
    container_name: jupyter-notebook
    ports:
      - "8888:8888"
    volumes:
      - ./:/home/jovyan/work
    environment:
      - JUPYTER_ENABLE_LAB=yes
    networks:
      - app-network
    profiles: ["analysis", "all"]

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: